use crate::client::GraphClient;
use crate::errors::GraphError;
use crate::nodes::{
    account, group, instance_profile, permission, policy, relationships, role, uid, user,
};
use iam_collector::CollectedData;
use iam_models::{Condition, Effect, IamInlinePolicy, PolicyStatement};
use neo4rs::Query;
use std::collections::HashSet;
use std::time::Instant;
use tracing::{debug, info, warn};

/// Configuration for a single ingestion run.
pub struct IngestConfig {
    /// Max queries per transaction batch.
    pub batch_size: usize,
    /// UUID v4 generated by the caller — uniquely identifies this snapshot.
    pub snapshot_id: String,
    /// AWS account ID.
    pub account_id: String,
    /// Human-readable account alias (optional).
    pub account_alias: Option<String>,
    /// When true, log queries instead of executing them.
    pub dry_run: bool,
    /// Shared id tagging every snapshot produced by one org-wide collection run.
    /// `None` for single-account (live/offline/hybrid) collection.
    pub org_collection_run_id: Option<String>,
}

impl Default for IngestConfig {
    fn default() -> Self {
        Self {
            batch_size: 500,
            snapshot_id: uuid::Uuid::new_v4().to_string(),
            account_id: String::new(),
            account_alias: None,
            dry_run: false,
            org_collection_run_id: None,
        }
    }
}

/// Statistics returned after a successful ingestion.
#[derive(Debug, Default)]
pub struct IngestStats {
    pub accounts_merged: u64,
    pub snapshots_created: u64,
    pub policies_merged: u64,
    pub roles_merged: u64,
    pub users_merged: u64,
    pub groups_merged: u64,
    pub instance_profiles_merged: u64,
    pub permissions_merged: u64,
    pub relationships_created: u64,
    pub duration_ms: u64,
}

/// Orchestrates all ingestion phases.
pub struct GraphIngester {
    client: GraphClient,
    config: IngestConfig,
}

impl GraphIngester {
    /// Create an ingester. Call [`GraphClient::initialize_schema`] before ingesting.
    pub fn new(client: GraphClient, config: IngestConfig) -> Self {
        Self { client, config }
    }

    /// Access the underlying `GraphClient` (e.g. for post-ingest queries in tests).
    pub fn client(&self) -> &GraphClient {
        &self.client
    }

    /// Consume the ingester and return the inner `GraphClient`.
    pub fn into_client(self) -> GraphClient {
        self.client
    }

    /// Ingest all IAM data from `data` into Neo4j in 6 sequential phases.
    pub async fn ingest(&self, data: &CollectedData) -> Result<IngestStats, GraphError> {
        let started = Instant::now();
        let mut stats = IngestStats::default();

        let snap_id = &self.config.snapshot_id;
        let acct_id = &self.config.account_id;

        // Phase 1 — global nodes
        info!(phase = 1, "ingesting global nodes");
        let mut phase1: Vec<Query> = Vec::new();
        phase1.push(account::merge_account_query(
            acct_id,
            self.config.account_alias.as_deref(),
        ));
        // Collect all distinct service prefixes from policy statements
        let prefixes = collect_service_prefixes(data);
        for prefix in &prefixes {
            phase1.push(permission::merge_aws_service_query(prefix));
        }
        self.execute_batch(1, phase1).await?;
        stats.accounts_merged = 1;

        // Phase 2 — snapshot node
        info!(phase = 2, "ingesting snapshot node");
        let collected_at = data.collection_timestamp.to_rfc3339();
        let is_partial = data.warnings.iter().any(|w| {
            matches!(
                w,
                iam_collector::CollectorWarning::InstanceProfilesMissing
                    | iam_collector::CollectorWarning::InlinePoliciesNotResolved
                    | iam_collector::CollectorWarning::WildcardsNotExpanded
                    | iam_collector::CollectorWarning::PartialData(_)
            )
        });
        let partial_reasons: Vec<String> = data
            .warnings
            .iter()
            .map(|w| match w {
                iam_collector::CollectorWarning::InstanceProfilesMissing => {
                    "instance profiles missing".to_string()
                }
                iam_collector::CollectorWarning::InlinePoliciesNotResolved => {
                    "some inline policies not resolved".to_string()
                }
                iam_collector::CollectorWarning::WildcardsNotExpanded => {
                    "some wildcards not expanded".to_string()
                }
                iam_collector::CollectorWarning::PartialData(msg) => msg.clone(),
            })
            .collect();
        let phase2 = vec![
            account::merge_snapshot_query(
                snap_id,
                acct_id,
                &collected_at,
                is_partial,
                partial_reasons,
                self.config.org_collection_run_id.as_deref(),
            ),
            account::snapshot_of_account_query(snap_id, acct_id),
        ];
        self.execute_batch(2, phase2).await?;
        stats.snapshots_created = 1;

        // Phase 3 — entity nodes
        info!(
            phase = 3,
            policies = data.policies.len(),
            roles = data.roles.len(),
            users = data.users.len(),
            groups = data.groups.len(),
            instance_profiles = data.instance_profiles.len(),
            "ingesting entity nodes"
        );
        let mut phase3: Vec<Query> = Vec::new();
        for p in &data.policies {
            phase3.push(policy::merge_policy_query(snap_id, acct_id, p));
        }
        for r in &data.roles {
            phase3.push(role::merge_role_query(snap_id, acct_id, r));
            for inline in &r.inline_policies {
                phase3.push(policy::merge_inline_policy_query(
                    snap_id, acct_id, &r.arn, inline,
                ));
            }
        }
        for u in &data.users {
            phase3.push(user::merge_user_query(snap_id, acct_id, u));
            for inline in &u.inline_policies {
                phase3.push(policy::merge_inline_policy_query(
                    snap_id, acct_id, &u.arn, inline,
                ));
            }
        }
        for g in &data.groups {
            phase3.push(group::merge_group_query(snap_id, acct_id, g));
            for inline in &g.inline_policies {
                phase3.push(policy::merge_inline_policy_query(
                    snap_id, acct_id, &g.arn, inline,
                ));
            }
        }
        for ip in &data.instance_profiles {
            phase3.push(instance_profile::merge_instance_profile_query(
                snap_id, acct_id, ip,
            ));
        }
        self.execute_batch(3, phase3).await?;
        stats.policies_merged = data.policies.len() as u64;
        stats.roles_merged = data.roles.len() as u64;
        stats.users_merged = data.users.len() as u64;
        stats.groups_merged = data.groups.len() as u64;
        stats.instance_profiles_merged = data.instance_profiles.len() as u64;

        // Phase 4 — permission nodes + ON_SERVICE relationships
        info!(phase = 4, "ingesting permission nodes");
        let mut phase4: Vec<Query> = Vec::new();
        let mut perm_count = 0u64;
        for p in &data.policies {
            if let Some(doc) = &p.document {
                for stmt in &doc.statement {
                    let effect_str = effect_str(&stmt.effect);
                    let resources = statement_resources(stmt);
                    let condition = stmt.condition.as_ref();
                    for action in &stmt.action {
                        for resource in &resources {
                            phase4.push(permission::merge_permission_query(
                                snap_id, acct_id, effect_str, action, resource, condition,
                            ));
                            let prefix = permission::service_prefix(action).to_string();
                            phase4.push(permission::permission_on_service_query(
                                snap_id, effect_str, action, resource, &prefix, condition,
                            ));
                            perm_count += 1;
                        }
                    }
                    if !stmt.not_action.is_empty() {
                        for resource in &resources {
                            phase4.push(permission::merge_excluded_permission_query(
                                snap_id,
                                acct_id,
                                effect_str,
                                resource,
                                &stmt.not_action,
                                condition,
                            ));
                            perm_count += 1;
                        }
                    }
                }
            }
        }
        for inlines in role_user_group_inline_sources(data) {
            for inline in inlines {
                for stmt in &inline.policy_document.statement {
                    let effect_str = effect_str(&stmt.effect);
                    let resources = statement_resources(stmt);
                    let condition = stmt.condition.as_ref();
                    for action in &stmt.action {
                        for resource in &resources {
                            phase4.push(permission::merge_permission_query(
                                snap_id, acct_id, effect_str, action, resource, condition,
                            ));
                            let prefix = permission::service_prefix(action).to_string();
                            phase4.push(permission::permission_on_service_query(
                                snap_id, effect_str, action, resource, &prefix, condition,
                            ));
                            perm_count += 1;
                        }
                    }
                    if !stmt.not_action.is_empty() {
                        for resource in &resources {
                            phase4.push(permission::merge_excluded_permission_query(
                                snap_id,
                                acct_id,
                                effect_str,
                                resource,
                                &stmt.not_action,
                                condition,
                            ));
                            perm_count += 1;
                        }
                    }
                }
            }
        }
        self.execute_batch(4, phase4).await?;
        stats.permissions_merged = perm_count;

        // Phase 5 — Snapshot INCLUDES entity nodes
        info!(phase = 5, "creating INCLUDES relationships");
        let mut phase5: Vec<Query> = Vec::new();
        for p in &data.policies {
            phase5.push(relationships::snapshot_includes_query(
                snap_id,
                &uid::entity_uid(snap_id, &p.arn),
            ));
        }
        for r in &data.roles {
            phase5.push(relationships::snapshot_includes_query(
                snap_id,
                &uid::entity_uid(snap_id, &r.arn),
            ));
        }
        for u in &data.users {
            phase5.push(relationships::snapshot_includes_query(
                snap_id,
                &uid::entity_uid(snap_id, &u.arn),
            ));
        }
        for ip in &data.instance_profiles {
            phase5.push(relationships::snapshot_includes_query(
                snap_id,
                &uid::entity_uid(snap_id, &ip.arn),
            ));
        }
        let phase5_count = phase5.len() as u64;
        self.execute_batch(5, phase5).await?;
        stats.relationships_created += phase5_count;

        // Phase 6 — entity relationships
        info!(phase = 6, "creating entity relationships");
        let mut phase6: Vec<Query> = Vec::new();
        let mut rel_count = 0u64;

        for r in &data.roles {
            for attached in &r.attached_managed_policies {
                phase6.push(relationships::has_attached_policy_query(
                    snap_id,
                    &r.arn,
                    &attached.policy_arn,
                ));
                rel_count += 1;
            }
            for inline in &r.inline_policies {
                phase6.push(relationships::has_inline_policy_query(
                    snap_id,
                    &r.arn,
                    &inline.policy_name,
                ));
                rel_count += 1;
            }
            if let Some(boundary) = &r.permissions_boundary {
                phase6.push(relationships::bounded_by_query(
                    snap_id,
                    &r.arn,
                    &boundary.permissions_boundary_arn,
                ));
                rel_count += 1;
            }
            // Trust policy principals
            if let Some(doc) = &r.assume_role_policy_document {
                for stmt in &doc.statement {
                    // Deny trust statements aren't evaluated (matches prior behavior —
                    // only Allow statements ever produced CAN_ASSUME edges).
                    if !matches!(stmt.effect, Effect::Allow) {
                        continue;
                    }

                    let principal_ids = stmt
                        .principal
                        .as_ref()
                        .map(extract_principal_ids)
                        .unwrap_or_default();
                    let principal_account = single_principal_account(&principal_ids);

                    let verdict = match &stmt.condition {
                        Some(cond) => classify_trust_condition(cond, principal_account),
                        None => TrustVerdict::AlwaysTrue,
                    };
                    // A condition that can never hold (e.g. a PrincipalAccount check
                    // that contradicts the listed principal's own account) means the
                    // statement never grants assumption — emit no edge at all.
                    if matches!(verdict, TrustVerdict::AlwaysFalse) {
                        continue;
                    }
                    let conditional = matches!(verdict, TrustVerdict::Runtime);

                    if !principal_ids.is_empty() {
                        for (kind, id) in principal_ids {
                            phase6.push(relationships::can_assume_query(
                                snap_id,
                                &kind,
                                &id,
                                &r.arn,
                                conditional,
                            ));
                            rel_count += 1;
                            // Bridge entity-to-entity only when the principal is an
                            // in-account IAM role/user ARN — the only kind that can
                            // resolve to another Role/User node in this snapshot.
                            if kind == "IamEntity" {
                                phase6.push(relationships::can_assume_role_query(
                                    snap_id,
                                    &id,
                                    &r.arn,
                                    conditional,
                                ));
                                rel_count += 1;
                            }
                        }
                    } else if stmt.not_principal.is_some() {
                        // `Allow NotPrincipal: [...]` allows every principal except the
                        // listed ones. We don't resolve the exclusion to concrete
                        // entities, so we represent "anyone but the excluded set" as a
                        // single Wildcard-kind edge rather than creating an edge from
                        // any of the excluded entities (which would be the over-assertion
                        // this issue exists to fix). The Wildcard kind never extends a
                        // CAN_ASSUME_ROLE chain, so it can't widen the escalation graph.
                        phase6.push(relationships::can_assume_query(
                            snap_id, "Wildcard", "*", &r.arn, true,
                        ));
                        rel_count += 1;
                    }
                }
            }
            // GRANTS from inline policies
            for inline in &r.inline_policies {
                for stmt in &inline.policy_document.statement {
                    push_inline_statement_grants(
                        &mut phase6,
                        &mut rel_count,
                        snap_id,
                        &r.arn,
                        &inline.policy_name,
                        stmt,
                    );
                }
            }
        }

        let group_arn_by_name: std::collections::HashMap<&str, &str> = data
            .groups
            .iter()
            .map(|g| (g.group_name.as_str(), g.arn.as_str()))
            .collect();

        for u in &data.users {
            for group_name in &u.group_list {
                if let Some(group_arn) = group_arn_by_name.get(group_name.as_str()) {
                    phase6.push(relationships::member_of_query(snap_id, &u.arn, group_arn));
                    rel_count += 1;
                }
            }
            for attached in &u.attached_managed_policies {
                phase6.push(relationships::has_attached_policy_query(
                    snap_id,
                    &u.arn,
                    &attached.policy_arn,
                ));
                rel_count += 1;
            }
            for inline in &u.inline_policies {
                phase6.push(relationships::has_inline_policy_query(
                    snap_id,
                    &u.arn,
                    &inline.policy_name,
                ));
                rel_count += 1;
                for stmt in &inline.policy_document.statement {
                    push_inline_statement_grants(
                        &mut phase6,
                        &mut rel_count,
                        snap_id,
                        &u.arn,
                        &inline.policy_name,
                        stmt,
                    );
                }
            }
            if let Some(boundary) = &u.permissions_boundary {
                phase6.push(relationships::bounded_by_query(
                    snap_id,
                    &u.arn,
                    &boundary.permissions_boundary_arn,
                ));
                rel_count += 1;
            }
        }

        for g in &data.groups {
            for attached in &g.attached_managed_policies {
                phase6.push(relationships::has_attached_policy_query(
                    snap_id,
                    &g.arn,
                    &attached.policy_arn,
                ));
                rel_count += 1;
            }
            for inline in &g.inline_policies {
                phase6.push(relationships::has_inline_policy_query(
                    snap_id,
                    &g.arn,
                    &inline.policy_name,
                ));
                rel_count += 1;
                for stmt in &inline.policy_document.statement {
                    push_inline_statement_grants(
                        &mut phase6,
                        &mut rel_count,
                        snap_id,
                        &g.arn,
                        &inline.policy_name,
                        stmt,
                    );
                }
            }
        }

        for ip in &data.instance_profiles {
            for r in &ip.roles {
                phase6.push(relationships::contains_role_query(snap_id, &ip.arn, &r.arn));
                rel_count += 1;
            }
        }

        // GRANTS from managed policies
        for p in &data.policies {
            if let Some(doc) = &p.document {
                for stmt in &doc.statement {
                    let eff = effect_str(&stmt.effect);
                    let resources = statement_resources(stmt);
                    let condition = stmt.condition.as_ref();
                    for action in &stmt.action {
                        for resource in &resources {
                            phase6.push(relationships::policy_grants_query(
                                snap_id, &p.arn, eff, action, resource, condition,
                            ));
                            rel_count += 1;
                        }
                    }
                    if !stmt.not_action.is_empty() {
                        for resource in &resources {
                            phase6.push(relationships::policy_grants_excluded_query(
                                snap_id,
                                &p.arn,
                                eff,
                                resource,
                                &stmt.not_action,
                                condition,
                            ));
                            rel_count += 1;
                        }
                    }
                }
            }
        }

        self.execute_batch(6, phase6).await?;
        stats.relationships_created += rel_count;
        stats.duration_ms = started.elapsed().as_millis() as u64;

        info!(
            duration_ms = stats.duration_ms,
            permissions = stats.permissions_merged,
            relationships = stats.relationships_created,
            "ingestion complete"
        );
        Ok(stats)
    }

    /// Execute a batch of queries, splitting into transactions of `batch_size`.
    async fn execute_batch(&self, phase: u8, queries: Vec<Query>) -> Result<(), GraphError> {
        if queries.is_empty() {
            return Ok(());
        }
        if self.config.dry_run {
            warn!(
                phase,
                count = queries.len(),
                "dry_run=true — skipping execution"
            );
            return Ok(());
        }
        let graph = self.client.inner();
        for chunk in queries.chunks(self.config.batch_size) {
            let started = Instant::now();
            let mut txn = graph.start_txn().await?;
            for q in chunk {
                txn.run(q.clone())
                    .await
                    .map_err(|e| GraphError::Ingestion {
                        phase,
                        cause: e.to_string(),
                    })?;
            }
            txn.commit().await.map_err(|e| GraphError::Ingestion {
                phase,
                cause: e.to_string(),
            })?;
            debug!(
                phase,
                batch_size = chunk.len(),
                duration_ms = started.elapsed().as_millis(),
                "batch committed"
            );
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn effect_str(effect: &Effect) -> &'static str {
    match effect {
        Effect::Allow => "Allow",
        Effect::Deny => "Deny",
    }
}

fn collect_service_prefixes(data: &CollectedData) -> Vec<String> {
    let mut prefixes = std::collections::HashSet::new();
    let collect_from_doc =
        |doc: &iam_models::PolicyDocument, set: &mut std::collections::HashSet<String>| {
            for stmt in &doc.statement {
                for action in &stmt.action {
                    let p = permission::service_prefix(action).to_string();
                    if p != "*" {
                        set.insert(p);
                    }
                }
            }
        };
    for p in &data.policies {
        if let Some(doc) = &p.document {
            collect_from_doc(doc, &mut prefixes);
        }
    }
    for r in &data.roles {
        for inline in &r.inline_policies {
            collect_from_doc(&inline.policy_document, &mut prefixes);
        }
    }
    for u in &data.users {
        for inline in &u.inline_policies {
            collect_from_doc(&inline.policy_document, &mut prefixes);
        }
    }
    for g in &data.groups {
        for inline in &g.inline_policies {
            collect_from_doc(&inline.policy_document, &mut prefixes);
        }
    }
    prefixes.into_iter().collect()
}

/// Inline policy slices for all roles, users, and groups.
fn role_user_group_inline_sources(data: &CollectedData) -> Vec<&[IamInlinePolicy]> {
    let mut out: Vec<&[IamInlinePolicy]> = Vec::new();
    for r in &data.roles {
        out.push(&r.inline_policies);
    }
    for u in &data.users {
        out.push(&u.inline_policies);
    }
    for g in &data.groups {
        out.push(&g.inline_policies);
    }
    out
}

/// Resources for a statement, defaulting to `["*"]` when none are listed.
fn statement_resources(stmt: &PolicyStatement) -> Vec<String> {
    if stmt.resource.is_empty() {
        vec!["*".to_string()]
    } else {
        stmt.resource.clone()
    }
}

/// Push GRANTS queries (action + NotAction-excluded) for one inline-policy statement.
fn push_inline_statement_grants(
    phase6: &mut Vec<Query>,
    rel_count: &mut u64,
    snap_id: &str,
    owner_arn: &str,
    inline_name: &str,
    stmt: &PolicyStatement,
) {
    let eff = effect_str(&stmt.effect);
    let resources = statement_resources(stmt);
    let condition = stmt.condition.as_ref();
    for action in &stmt.action {
        for resource in &resources {
            phase6.push(relationships::inline_grants_query(
                snap_id,
                owner_arn,
                inline_name,
                eff,
                action,
                resource,
                condition,
            ));
            *rel_count += 1;
        }
    }
    if !stmt.not_action.is_empty() {
        for resource in &resources {
            phase6.push(relationships::inline_grants_excluded_query(
                snap_id,
                owner_arn,
                inline_name,
                eff,
                resource,
                &stmt.not_action,
                condition,
            ));
            *rel_count += 1;
        }
    }
}

/// Outcome of evaluating a trust-policy `Condition` block against the resolved
/// account of the statement's principal, where that's known.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum TrustVerdict {
    /// The condition cannot fail given the principal — evaluate as unconditional.
    AlwaysTrue,
    /// The condition can never hold given the principal — the statement never
    /// actually grants assumption.
    AlwaysFalse,
    /// Depends on runtime values (e.g. `sts:ExternalId`, MFA) we can't evaluate
    /// from collected data — keep `conditional = true`.
    Runtime,
}

/// Evaluate the small set of deterministic trust-policy conditions we understand.
///
/// Only `StringEquals`/`StringEqualsIgnoreCase` on `aws:PrincipalAccount` against a
/// principal whose account is statically known (a concrete in-account or
/// cross-account ARN, not a Service/Federated/Wildcard principal) is deterministic:
/// the condition is consistent or contradictory with the principal's own account
/// regardless of any runtime value. Everything else (multiple/unknown operators,
/// other condition keys, or an unresolvable principal account) stays `Runtime`.
fn classify_trust_condition(
    condition: &Condition,
    principal_account: Option<&str>,
) -> TrustVerdict {
    if condition.is_empty() {
        return TrustVerdict::AlwaysTrue;
    }
    for (operator, keys) in condition {
        let op = operator.to_lowercase();
        if op != "stringequals" && op != "stringequalsignorecase" {
            return TrustVerdict::Runtime;
        }
        for (key, values) in keys {
            if key.to_lowercase() != "aws:principalaccount" {
                return TrustVerdict::Runtime;
            }
            let Some(account) = principal_account else {
                return TrustVerdict::Runtime;
            };
            if !values.0.iter().any(|v| v == account) {
                return TrustVerdict::AlwaysFalse;
            }
        }
    }
    TrustVerdict::AlwaysTrue
}

/// Account segment of an ARN (`arn:aws:iam::ACCOUNT:...`), or `None` if absent/empty.
fn arn_account(arn: &str) -> Option<&str> {
    match arn.split(':').nth(4) {
        Some(s) if !s.is_empty() => Some(s),
        _ => None,
    }
}

/// The single account shared by every in-account principal id in the list, or
/// `None` if the accounts are unknown or not all identical (ambiguous).
fn single_principal_account(principal_ids: &[(String, String)]) -> Option<&str> {
    let mut accounts: HashSet<&str> = HashSet::new();
    for (kind, id) in principal_ids {
        if kind == "IamEntity" || kind == "AssumedRole" {
            accounts.insert(arn_account(id)?);
        }
    }
    if accounts.len() == 1 {
        accounts.into_iter().next()
    } else {
        None
    }
}

/// Extract `(kind, id)` pairs from a trust-policy principal block.
///
/// Reads the block key (`AWS`, `Service`, `Federated`, `CanonicalUser`) to set
/// the kind accurately rather than re-inferring it from the id string shape.
fn extract_principal_ids(principal: &serde_json::Value) -> Vec<(String, String)> {
    let mut results = Vec::new();
    match principal {
        serde_json::Value::String(s) => {
            let kind = if s == "*" { "Wildcard" } else { "Unknown" };
            results.push((kind.to_string(), s.clone()));
        }
        serde_json::Value::Object(map) => {
            for (key, val) in map {
                let raw_ids: Vec<String> = match val {
                    serde_json::Value::String(s) => vec![s.clone()],
                    serde_json::Value::Array(arr) => arr
                        .iter()
                        .filter_map(|v| v.as_str().map(String::from))
                        .collect(),
                    _ => continue,
                };
                for id in raw_ids {
                    results.push((principal_kind(key, &id), id));
                }
            }
        }
        _ => {}
    }
    results
}

/// Derive principal kind from the trust policy block key and the id value.
fn principal_kind(key: &str, id: &str) -> String {
    match key {
        "Service" => "Service",
        "Federated" => "Federated",
        "CanonicalUser" => "CanonicalUser",
        "AWS" if id == "*" => "Wildcard",
        "AWS" if id.contains(":assumed-role/") => "AssumedRole",
        "AWS" => "IamEntity",
        _ => "Unknown",
    }
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_principals_service_key_returns_service_kind() {
        let principal = serde_json::json!({"Service": "ec2.amazonaws.com"});

        let results = extract_principal_ids(&principal);

        assert_eq!(
            results,
            vec![("Service".to_string(), "ec2.amazonaws.com".to_string())]
        );
    }

    #[test]
    fn extract_principals_aws_root_returns_iam_entity_kind() {
        let principal = serde_json::json!({"AWS": "arn:aws:iam::123456789012:root"});

        let results = extract_principal_ids(&principal);

        assert_eq!(
            results,
            vec![(
                "IamEntity".to_string(),
                "arn:aws:iam::123456789012:root".to_string()
            )]
        );
    }

    #[test]
    fn extract_principals_aws_wildcard_returns_wildcard_kind() {
        let principal = serde_json::json!({"AWS": "*"});

        let results = extract_principal_ids(&principal);

        assert_eq!(results, vec![("Wildcard".to_string(), "*".to_string())]);
    }

    #[test]
    fn extract_principals_federated_returns_federated_kind() {
        let principal = serde_json::json!({"Federated": "cognito-identity.amazonaws.com"});

        let results = extract_principal_ids(&principal);

        assert_eq!(
            results,
            vec![(
                "Federated".to_string(),
                "cognito-identity.amazonaws.com".to_string()
            )]
        );
    }

    #[test]
    fn extract_principals_assumed_role_arn_returns_assumed_role_kind() {
        let principal =
            serde_json::json!({"AWS": "arn:aws:sts::123456789012:assumed-role/MyRole/session"});

        let results = extract_principal_ids(&principal);

        assert_eq!(
            results,
            vec![(
                "AssumedRole".to_string(),
                "arn:aws:sts::123456789012:assumed-role/MyRole/session".to_string()
            )]
        );
    }

    #[test]
    fn extract_principals_root_string_wildcard_returns_wildcard_kind() {
        let principal = serde_json::json!("*");

        let results = extract_principal_ids(&principal);

        assert_eq!(results, vec![("Wildcard".to_string(), "*".to_string())]);
    }

    #[test]
    fn extract_principals_array_value_returns_multiple_entries() {
        let principal = serde_json::json!({
            "AWS": [
                "arn:aws:iam::111:root",
                "arn:aws:iam::222:root"
            ]
        });

        let results = extract_principal_ids(&principal);

        assert_eq!(results.len(), 2);
        assert!(results.iter().all(|(kind, _)| kind == "IamEntity"));
    }

    #[test]
    fn arn_account_extracts_account_segment() {
        assert_eq!(
            arn_account("arn:aws:iam::123456789012:role/X"),
            Some("123456789012")
        );
    }

    #[test]
    fn arn_account_returns_none_for_non_arn() {
        assert_eq!(arn_account("not-an-arn"), None);
        assert_eq!(arn_account("ec2.amazonaws.com"), None);
    }

    #[test]
    fn single_principal_account_returns_account_for_uniform_iam_entities() {
        let ids = vec![
            ("IamEntity".to_string(), "arn:aws:iam::111:root".to_string()),
            (
                "IamEntity".to_string(),
                "arn:aws:iam::111:role/X".to_string(),
            ),
        ];
        assert_eq!(single_principal_account(&ids), Some("111"));
    }

    #[test]
    fn single_principal_account_returns_none_for_mixed_accounts() {
        let ids = vec![
            ("IamEntity".to_string(), "arn:aws:iam::111:root".to_string()),
            ("IamEntity".to_string(), "arn:aws:iam::222:root".to_string()),
        ];
        assert_eq!(single_principal_account(&ids), None);
    }

    #[test]
    fn single_principal_account_returns_none_for_service_principal() {
        let ids = vec![("Service".to_string(), "ec2.amazonaws.com".to_string())];
        assert_eq!(single_principal_account(&ids), None);
    }

    #[test]
    fn classify_trust_condition_empty_is_always_true() {
        let condition: Condition = std::collections::HashMap::new();
        assert_eq!(
            classify_trust_condition(&condition, Some("111")),
            TrustVerdict::AlwaysTrue
        );
    }

    #[test]
    fn classify_trust_condition_matching_principal_account_is_always_true() {
        let condition: Condition = std::collections::HashMap::from([(
            "StringEquals".to_string(),
            std::collections::HashMap::from([(
                "aws:PrincipalAccount".to_string(),
                iam_models::ConditionValues(vec!["111".to_string()]),
            )]),
        )]);
        assert_eq!(
            classify_trust_condition(&condition, Some("111")),
            TrustVerdict::AlwaysTrue
        );
    }

    #[test]
    fn classify_trust_condition_mismatched_principal_account_is_always_false() {
        let condition: Condition = std::collections::HashMap::from([(
            "StringEquals".to_string(),
            std::collections::HashMap::from([(
                "aws:PrincipalAccount".to_string(),
                iam_models::ConditionValues(vec!["222".to_string()]),
            )]),
        )]);
        assert_eq!(
            classify_trust_condition(&condition, Some("111")),
            TrustVerdict::AlwaysFalse
        );
    }

    #[test]
    fn classify_trust_condition_unresolvable_principal_is_runtime() {
        let condition: Condition = std::collections::HashMap::from([(
            "StringEquals".to_string(),
            std::collections::HashMap::from([(
                "aws:PrincipalAccount".to_string(),
                iam_models::ConditionValues(vec!["111".to_string()]),
            )]),
        )]);
        assert_eq!(
            classify_trust_condition(&condition, None),
            TrustVerdict::Runtime
        );
    }

    #[test]
    fn classify_trust_condition_external_id_is_runtime() {
        let condition: Condition = std::collections::HashMap::from([(
            "StringEquals".to_string(),
            std::collections::HashMap::from([(
                "sts:ExternalId".to_string(),
                iam_models::ConditionValues(vec!["secret".to_string()]),
            )]),
        )]);
        assert_eq!(
            classify_trust_condition(&condition, Some("111")),
            TrustVerdict::Runtime
        );
    }

    #[test]
    fn classify_trust_condition_unknown_operator_is_runtime() {
        let condition: Condition = std::collections::HashMap::from([(
            "DateGreaterThan".to_string(),
            std::collections::HashMap::from([(
                "aws:CurrentTime".to_string(),
                iam_models::ConditionValues(vec!["2024-01-01T00:00:00Z".to_string()]),
            )]),
        )]);
        assert_eq!(
            classify_trust_condition(&condition, Some("111")),
            TrustVerdict::Runtime
        );
    }
}
