use crate::client::GraphClient;
use crate::errors::GraphError;
use crate::nodes::{
    account, group, instance_profile, permission, policy, relationships, role, uid, user,
};
use iam_collector::CollectedData;
use iam_models::{Effect, IamInlinePolicy};
use neo4rs::Query;
use std::time::Instant;
use tracing::{debug, info, warn};

/// Configuration for a single ingestion run.
pub struct IngestConfig {
    /// Max queries per transaction batch.
    pub batch_size: usize,
    /// UUID v4 generated by the caller — uniquely identifies this snapshot.
    pub snapshot_id: String,
    /// AWS account ID.
    pub account_id: String,
    /// Human-readable account alias (optional).
    pub account_alias: Option<String>,
    /// When true, log queries instead of executing them.
    pub dry_run: bool,
}

impl Default for IngestConfig {
    fn default() -> Self {
        Self {
            batch_size: 500,
            snapshot_id: uuid::Uuid::new_v4().to_string(),
            account_id: String::new(),
            account_alias: None,
            dry_run: false,
        }
    }
}

/// Statistics returned after a successful ingestion.
#[derive(Debug, Default)]
pub struct IngestStats {
    pub accounts_merged: u64,
    pub snapshots_created: u64,
    pub policies_merged: u64,
    pub roles_merged: u64,
    pub users_merged: u64,
    pub groups_merged: u64,
    pub instance_profiles_merged: u64,
    pub permissions_merged: u64,
    pub relationships_created: u64,
    pub duration_ms: u64,
}

/// Orchestrates all ingestion phases.
pub struct GraphIngester {
    client: GraphClient,
    config: IngestConfig,
}

impl GraphIngester {
    /// Create an ingester. Call [`GraphClient::initialize_schema`] before ingesting.
    pub fn new(client: GraphClient, config: IngestConfig) -> Self {
        Self { client, config }
    }

    /// Access the underlying `GraphClient` (e.g. for post-ingest queries in tests).
    pub fn client(&self) -> &GraphClient {
        &self.client
    }

    /// Consume the ingester and return the inner `GraphClient`.
    pub fn into_client(self) -> GraphClient {
        self.client
    }

    /// Ingest all IAM data from `data` into Neo4j in 6 sequential phases.
    pub async fn ingest(&self, data: &CollectedData) -> Result<IngestStats, GraphError> {
        let started = Instant::now();
        let mut stats = IngestStats::default();

        let snap_id = &self.config.snapshot_id;
        let acct_id = &self.config.account_id;

        // Phase 1 — global nodes
        info!(phase = 1, "ingesting global nodes");
        let mut phase1: Vec<Query> = Vec::new();
        phase1.push(account::merge_account_query(
            acct_id,
            self.config.account_alias.as_deref(),
        ));
        // Collect all distinct service prefixes from policy statements
        let prefixes = collect_service_prefixes(data);
        for prefix in &prefixes {
            phase1.push(permission::merge_aws_service_query(prefix));
        }
        self.execute_batch(1, phase1).await?;
        stats.accounts_merged = 1;

        // Phase 2 — snapshot node
        info!(phase = 2, "ingesting snapshot node");
        let collected_at = data.collection_timestamp.to_rfc3339();
        let phase2 = vec![
            account::merge_snapshot_query(snap_id, acct_id, &collected_at, false),
            account::snapshot_of_account_query(snap_id, acct_id),
        ];
        self.execute_batch(2, phase2).await?;
        stats.snapshots_created = 1;

        // Phase 3 — entity nodes
        info!(
            phase = 3,
            policies = data.policies.len(),
            roles = data.roles.len(),
            users = data.users.len(),
            groups = data.groups.len(),
            instance_profiles = data.instance_profiles.len(),
            "ingesting entity nodes"
        );
        let mut phase3: Vec<Query> = Vec::new();
        for p in &data.policies {
            phase3.push(policy::merge_policy_query(snap_id, acct_id, p));
        }
        for r in &data.roles {
            phase3.push(role::merge_role_query(snap_id, acct_id, r));
            for inline in &r.inline_policies {
                phase3.push(policy::merge_inline_policy_query(
                    snap_id, acct_id, &r.arn, inline,
                ));
            }
        }
        for u in &data.users {
            phase3.push(user::merge_user_query(snap_id, acct_id, u));
            for inline in &u.inline_policies {
                phase3.push(policy::merge_inline_policy_query(
                    snap_id, acct_id, &u.arn, inline,
                ));
            }
        }
        for g in &data.groups {
            phase3.push(group::merge_group_query(snap_id, acct_id, g));
            for inline in &g.inline_policies {
                phase3.push(policy::merge_inline_policy_query(
                    snap_id, acct_id, &g.arn, inline,
                ));
            }
        }
        for ip in &data.instance_profiles {
            phase3.push(instance_profile::merge_instance_profile_query(
                snap_id, acct_id, ip,
            ));
        }
        self.execute_batch(3, phase3).await?;
        stats.policies_merged = data.policies.len() as u64;
        stats.roles_merged = data.roles.len() as u64;
        stats.users_merged = data.users.len() as u64;
        stats.groups_merged = data.groups.len() as u64;
        stats.instance_profiles_merged = data.instance_profiles.len() as u64;

        // Phase 4 — permission nodes + ON_SERVICE relationships
        info!(phase = 4, "ingesting permission nodes");
        let mut phase4: Vec<Query> = Vec::new();
        let mut perm_count = 0u64;
        for p in &data.policies {
            if let Some(doc) = &p.document {
                for stmt in &doc.statement {
                    let effect_str = effect_str(&stmt.effect);
                    let resources = if stmt.resource.is_empty() {
                        vec!["*".to_string()]
                    } else {
                        stmt.resource.clone()
                    };
                    for action in &stmt.action {
                        for resource in &resources {
                            phase4.push(permission::merge_permission_query(
                                snap_id, acct_id, effect_str, action, resource,
                            ));
                            let prefix = permission::service_prefix(action).to_string();
                            phase4.push(permission::permission_on_service_query(
                                snap_id, effect_str, action, resource, &prefix,
                            ));
                            perm_count += 1;
                        }
                    }
                }
            }
        }
        for inlines in role_user_group_inline_sources(data) {
            for inline in inlines {
                for stmt in &inline.policy_document.statement {
                    let effect_str = effect_str(&stmt.effect);
                    let resources = if stmt.resource.is_empty() {
                        vec!["*".to_string()]
                    } else {
                        stmt.resource.clone()
                    };
                    for action in &stmt.action {
                        for resource in &resources {
                            phase4.push(permission::merge_permission_query(
                                snap_id, acct_id, effect_str, action, resource,
                            ));
                            let prefix = permission::service_prefix(action).to_string();
                            phase4.push(permission::permission_on_service_query(
                                snap_id, effect_str, action, resource, &prefix,
                            ));
                            perm_count += 1;
                        }
                    }
                }
            }
        }
        self.execute_batch(4, phase4).await?;
        stats.permissions_merged = perm_count;

        // Phase 5 — Snapshot INCLUDES entity nodes
        info!(phase = 5, "creating INCLUDES relationships");
        let mut phase5: Vec<Query> = Vec::new();
        for p in &data.policies {
            phase5.push(relationships::snapshot_includes_query(
                snap_id,
                &uid::entity_uid(snap_id, &p.arn),
            ));
        }
        for r in &data.roles {
            phase5.push(relationships::snapshot_includes_query(
                snap_id,
                &uid::entity_uid(snap_id, &r.arn),
            ));
        }
        for u in &data.users {
            phase5.push(relationships::snapshot_includes_query(
                snap_id,
                &uid::entity_uid(snap_id, &u.arn),
            ));
        }
        for ip in &data.instance_profiles {
            phase5.push(relationships::snapshot_includes_query(
                snap_id,
                &uid::entity_uid(snap_id, &ip.arn),
            ));
        }
        let phase5_count = phase5.len() as u64;
        self.execute_batch(5, phase5).await?;
        stats.relationships_created += phase5_count;

        // Phase 6 — entity relationships
        info!(phase = 6, "creating entity relationships");
        let mut phase6: Vec<Query> = Vec::new();
        let mut rel_count = 0u64;

        for r in &data.roles {
            for attached in &r.attached_managed_policies {
                phase6.push(relationships::has_attached_policy_query(
                    snap_id,
                    &r.arn,
                    &attached.policy_arn,
                ));
                rel_count += 1;
            }
            for inline in &r.inline_policies {
                phase6.push(relationships::has_inline_policy_query(
                    snap_id,
                    &r.arn,
                    &inline.policy_name,
                ));
                rel_count += 1;
            }
            if let Some(boundary) = &r.permissions_boundary {
                phase6.push(relationships::bounded_by_query(
                    snap_id,
                    &r.arn,
                    &boundary.permissions_boundary_arn,
                ));
                rel_count += 1;
            }
            // Trust policy principals
            if let Some(doc) = &r.assume_role_policy_document {
                for stmt in &doc.statement {
                    if let Some(principal) = &stmt.principal {
                        for id in extract_principal_ids(principal) {
                            phase6.push(relationships::can_assume_query(snap_id, &id, &r.arn));
                            rel_count += 1;
                        }
                    }
                }
            }
            // GRANTS from inline policies
            for inline in &r.inline_policies {
                for stmt in &inline.policy_document.statement {
                    let eff = effect_str(&stmt.effect);
                    let resources = if stmt.resource.is_empty() {
                        vec!["*".to_string()]
                    } else {
                        stmt.resource.clone()
                    };
                    for action in &stmt.action {
                        for resource in &resources {
                            phase6.push(relationships::inline_grants_query(
                                snap_id,
                                &r.arn,
                                &inline.policy_name,
                                eff,
                                action,
                                resource,
                            ));
                            rel_count += 1;
                        }
                    }
                }
            }
        }

        for u in &data.users {
            for attached in &u.attached_managed_policies {
                phase6.push(relationships::has_attached_policy_query(
                    snap_id,
                    &u.arn,
                    &attached.policy_arn,
                ));
                rel_count += 1;
            }
            for inline in &u.inline_policies {
                phase6.push(relationships::has_inline_policy_query(
                    snap_id,
                    &u.arn,
                    &inline.policy_name,
                ));
                rel_count += 1;
            }
            if let Some(boundary) = &u.permissions_boundary {
                phase6.push(relationships::bounded_by_query(
                    snap_id,
                    &u.arn,
                    &boundary.permissions_boundary_arn,
                ));
                rel_count += 1;
            }
        }

        for g in &data.groups {
            for attached in &g.attached_managed_policies {
                phase6.push(relationships::has_attached_policy_query(
                    snap_id,
                    &g.arn,
                    &attached.policy_arn,
                ));
                rel_count += 1;
            }
            for inline in &g.inline_policies {
                phase6.push(relationships::has_inline_policy_query(
                    snap_id,
                    &g.arn,
                    &inline.policy_name,
                ));
                rel_count += 1;
            }
        }

        for ip in &data.instance_profiles {
            for r in &ip.roles {
                phase6.push(relationships::contains_role_query(snap_id, &ip.arn, &r.arn));
                rel_count += 1;
            }
        }

        // GRANTS from managed policies
        for p in &data.policies {
            if let Some(doc) = &p.document {
                for stmt in &doc.statement {
                    let eff = effect_str(&stmt.effect);
                    let resources = if stmt.resource.is_empty() {
                        vec!["*".to_string()]
                    } else {
                        stmt.resource.clone()
                    };
                    for action in &stmt.action {
                        for resource in &resources {
                            phase6.push(relationships::policy_grants_query(
                                snap_id, &p.arn, eff, action, resource,
                            ));
                            rel_count += 1;
                        }
                    }
                }
            }
        }

        self.execute_batch(6, phase6).await?;
        stats.relationships_created += rel_count;
        stats.duration_ms = started.elapsed().as_millis() as u64;

        info!(
            duration_ms = stats.duration_ms,
            permissions = stats.permissions_merged,
            relationships = stats.relationships_created,
            "ingestion complete"
        );
        Ok(stats)
    }

    /// Execute a batch of queries, splitting into transactions of `batch_size`.
    async fn execute_batch(&self, phase: u8, queries: Vec<Query>) -> Result<(), GraphError> {
        if queries.is_empty() {
            return Ok(());
        }
        if self.config.dry_run {
            warn!(
                phase,
                count = queries.len(),
                "dry_run=true — skipping execution"
            );
            return Ok(());
        }
        let graph = self.client.inner();
        for chunk in queries.chunks(self.config.batch_size) {
            let started = Instant::now();
            let mut txn = graph.start_txn().await?;
            for q in chunk {
                txn.run(q.clone())
                    .await
                    .map_err(|e| GraphError::Ingestion {
                        phase,
                        cause: e.to_string(),
                    })?;
            }
            txn.commit().await.map_err(|e| GraphError::Ingestion {
                phase,
                cause: e.to_string(),
            })?;
            debug!(
                phase,
                batch_size = chunk.len(),
                duration_ms = started.elapsed().as_millis(),
                "batch committed"
            );
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn effect_str(effect: &Effect) -> &'static str {
    match effect {
        Effect::Allow => "Allow",
        Effect::Deny => "Deny",
    }
}

fn collect_service_prefixes(data: &CollectedData) -> Vec<String> {
    let mut prefixes = std::collections::HashSet::new();
    let collect_from_doc =
        |doc: &iam_models::PolicyDocument, set: &mut std::collections::HashSet<String>| {
            for stmt in &doc.statement {
                for action in &stmt.action {
                    let p = permission::service_prefix(action).to_string();
                    if p != "*" {
                        set.insert(p);
                    }
                }
            }
        };
    for p in &data.policies {
        if let Some(doc) = &p.document {
            collect_from_doc(doc, &mut prefixes);
        }
    }
    for r in &data.roles {
        for inline in &r.inline_policies {
            collect_from_doc(&inline.policy_document, &mut prefixes);
        }
    }
    for u in &data.users {
        for inline in &u.inline_policies {
            collect_from_doc(&inline.policy_document, &mut prefixes);
        }
    }
    for g in &data.groups {
        for inline in &g.inline_policies {
            collect_from_doc(&inline.policy_document, &mut prefixes);
        }
    }
    prefixes.into_iter().collect()
}

/// Inline policy slices for all roles, users, and groups.
fn role_user_group_inline_sources(data: &CollectedData) -> Vec<&[IamInlinePolicy]> {
    let mut out: Vec<&[IamInlinePolicy]> = Vec::new();
    for r in &data.roles {
        out.push(&r.inline_policies);
    }
    for u in &data.users {
        out.push(&u.inline_policies);
    }
    for g in &data.groups {
        out.push(&g.inline_policies);
    }
    out
}

/// Extract string principal IDs from a serde_json principal block.
fn extract_principal_ids(principal: &serde_json::Value) -> Vec<String> {
    let mut ids = Vec::new();
    match principal {
        serde_json::Value::String(s) => ids.push(s.clone()),
        serde_json::Value::Object(map) => {
            for val in map.values() {
                match val {
                    serde_json::Value::String(s) => ids.push(s.clone()),
                    serde_json::Value::Array(arr) => {
                        for item in arr {
                            if let serde_json::Value::String(s) = item {
                                ids.push(s.clone());
                            }
                        }
                    }
                    _ => {}
                }
            }
        }
        _ => {}
    }
    ids
}
