[package]
name = "iam-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config   = { workspace = true }
aws-sdk-iam  = { workspace = true }
chrono       = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }
async-trait  = { workspace = true }
thiserror    = { workspace = true }
tracing      = { workspace = true }
iam-models   = { path = "../iam-models" }
iam-expander = { path = "../iam-expander" }

[dev-dependencies]
aws-smithy-mocks  = { workspace = true }
aws-sdk-iam       = { workspace = true, features = ["test-util"] }
tokio             = { workspace = true }
pretty_assertions = { workspace = true }
chrono            = { workspace = true }
testcontainers    = "0.27"
reqwest           = { version = "0.13", features = ["json"] }
